version: '3.9'

volumes:
  typesense-data:

services:
  nginx:
    container_name: nginx_ewalch
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../app/public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: php_ewalch
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    networks: [default]
    ports:
      - '9000:9000'
    env_file:
      - ./environment/api.env
      - path: ./environment/api.env.local
        required: false
    volumes:
      - ../app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini

  database:
    image: postgres:16
    env_file: ['./environment/db.env']
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer_ewalch
    image: adminer
    depends_on:
      - database
    ports:
      - '8081:8080'
    hostname: adminer.ewalch.test
